"""new id

Revision ID: b949487557f0
Revises: acb62bea35c0
Create Date: 2025-05-10 16:13:55.952029

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "b949487557f0"
down_revision: Union[str, None] = "acb62bea35c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
