name: Python CI

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12.4
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.4"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff black mypy

    - name: Run Black formatter
      run: |
        black --check --diff .

    - name: Run Ruff linter
      run: |
        ruff check .

    - name: Run Mypy type checker
      run: |
        mypy .
